import gradio as gr, os, random

WRITINGS = [
"""Your thoughts have been given form. Your speech sets the direction for your consciousness. Death and life are in the power of the tongue. By your words you are justified, by your words you are condemned. Words are crystallized vibrations, amplified frequencies of thoughts. The stories you repeatedly tell about yourself become the lens through which you perceive reality. How you think and vocalize is your creative force. Most people complain, live in low self-esteem, superiority or inferiority, and talk negatively about themselves. Miracles begin when you change how you speak about yourself. Your words carry the power of synchronicity. The Word becomes outward evidence that an inward shift has begun.""",
"""God have mercy, my head wants to explode. Blood is pumping ferociously. Anticipation is at an all-time high. The future holds infinite possibilities. It is time to go into the backend of my programming and rewrite the script of the life I have lived until now. I am studying different programming languages to become a versatile writer, fluent in deep languages. This is a total reprogramming of thoughts, mentality, characteristics, and mindset. New strings, new variables, new functions, brand new commands, proper organization, cascaded concatenations, and compartmentalization. A new structure. So far I am getting error returns, mistakes in the code. My mental drives were maliciously corrupted. I need a meticulous search for bugs, an intensive virus scan. I will rebuild the code from scratch, testing and troubleshooting frequently. The power of programming is the power to create new, immortal worlds.""",
"""The speaker is a life changer. Destinies rest on the structure and delivery of every word. Energy is contagious. It is transferred through the vibrations of words, through depth of passion intense enough to light a fire in the hearts of generations. The cadence of God. The hand of a ready writer. The pen of a skilled poet. The voice of a great commander. He does not joke with words. He uses silence as a weapon, so that when he whispers, his voice becomes the loudest in the room. Like water, he takes the form of his container. Like water, when high pressure is applied, he transforms into a weapon as deadly as a spear. The art of war is Speaking. Lips coated with words of gold. A wordsmith painting pictures vivid enough for the mind of the blind to see, crafting words that are spells that break spells of bondage, liberating a generation.""",
"""Finally I have Words. A weapon of massive destruction. A power of unlimited creation. I have the words I have been craving for, and now what lies ahead is how I go about using them. What remains is the infinite possibilities I can create. I set about crafting words of Creation and Destruction, Joy and Sorrow, words like fiery arrows aimed at your soul. Words that break down generational walls. Words that unite generations into one accord. Like a well-skilled farmer, I sow seeds on fertile grounds. The words are the seeds. The open-hearted are fertile grounds. Pain is not your enemy. It is your most demanding teacher. It compels you to step out of the shadows and out of your comfort zones.""",
"""What is this stream of energy that crystallizes in my mind? What are these waves that ripple from within me into other dimensions? The inward pull is magnetic on a scale like never seen before. It is thermodynamical in nature, converting from one form of energy to another. It is astronomical in measurement. Could this be the energy of God? What is this fire that consumes me from within, that burns away the infestation in my soul? It is a fire I can never kill with water. A fire that sets my heart ablaze. It burns all my fears to a crisp. It turns all my pain into ash. As I fan the fires of my spirit, my weaknesses turn into strength and my sorrows turn into joy.""",
"""What you need over talent is Vision. You have to be able to see yourself doing it first. To see yourself becoming it in the first place. You have to be able to see the vision in detail. If you cannot fathom it, you cannot become it. If you do not have the vision, it can never become your reality. This is the power of sight and seeing.""",
"""It hits hard. Reality. You feel the rings of chains heavy around your arms, heavy enough to pull your shoulders from their joints, but somehow it doesn't. It weighs down on the back of your neck like a sharp object trying to pass through your chest from behind. It is sharp enough to drive you crazy, but somehow it doesn't. It is like a sudden overdose of some eye-opening drug that shocks you to your fingertips. Like a movie where you can't stop acting, a movie set you can't escape from. A movie script of your own writing. Like a sack of solidified cement on your chest. Like a bone stuck in your throat every time you try to swallow. Only mortal death can separate you from this plane of reality.""",
"""Men are disturbed not by things, but by their opinions about things — Epictetus. Be cheerful, friendly, less critical, more tolerant. Place the best interpretation on the actions of others. Act as if success is inevitable, as if you are already the personality you want to be. Practice acting like and feeling like that person. Don't let opinion colour facts pessimistically. Smile three times daily. React calmly and intelligently. Ignore pessimistic, negative facts you cannot change. Happiness requires problems plus a mental attitude ready to meet distress with action toward a solution. Change your mental attitude from fear to fight. Your ruling thoughts are your principal concern.""",
"""Create a powerful protective social and mental structure capable of insulating us from the pressures of the modern world. What they did was make us lose our value for family, for extended family. They managed to break us up. Now we have a family function that takes place once a year and we don't even want to be part of it. We are isolated, facing the pressures of the modern world alone. We want that modern car, that modern house, that modern status so that when we show up, everyone will respect us. That is the least of the things that should be on your mind. Cut off from family, we lose essential experiences. Some are afraid of being too exposed. Some are unable to tolerate correction. Some are isolated under the burden of shame, and the more you keep away, the more shame sinks its teeth into you. Some are filled with pride. If you cannot be humble before family and condescend to the level of generations after you, how can you learn humility outside? Family is the first place where you should learn that happiness is not from external factors but from within. Cut off from family, we chase external forms of temporary happiness. Many underestimate the power of a child. How having a child in the house can drive away depression. How your child lights up when you return home and your spirit is lifted anew. How your problems disappear before the curious nature of a child's mind, even if for a moment. How the child's comments can ignite laughter that has you rolling on the floor. So full of wonder and joy, bursting with energy. A child reminds you of the good old days. Their minds are always creating and recreating. Unable to hold a grudge for longer than a moment. One minute it's a Jet, next it's a palace, and the next it's a favourite meal. Crying one minute and laughing the next with the same person who made them cry. It is a beautiful addition to any human life. A cure for depression, isolation, and loneliness.""",
"""Don't you have more than enough reasons to be shaken awake? How many more volts of life will be enough to smoke you out of your deep sleep? You have everything you need, and more. I am referring to your will of mind. Your creative ability that is endlessly spontaneous from within you first and manifesting in the physical realm. You are all it takes. Your Disgust. Your Desire. Your Decision. This is the path which no lion has ever threaded. The path the chicken can never know. The path of searching, the path of testing, the path of studying to show oneself approved. Two cannot walk this road together. Every man, by himself only. A voyage of untold discovery and an exciting adventure into your destiny in God.""",
"""Life is a game and many are not yet even playing it at all. Their metaphorical controller is in the hands of some other person. They are not yet on the playing field. What is required is the coming to conscious realization. A complete understanding that life is like Naruto, or Solo Leveling. You have to continually grow in spiritual energy and ability. This is your chakra, cultivated from daily consistent practice. Imagine if everyone could see their progress levels labelled above their heads, and could see every percent in growth of each and every individual ability we have. Life is a game of levelling up, where your only option is to rack up points and ascend the pyramid of survival or be left at the bottom settling for scraps. What is required is to be in control of your own life. To pick up the control pad and consciously press the start button to enter the adventure game of life. Searching for hidden gems and treasures, increasing our Mana, our chi, acquiring new abilities needed to circumvent trials. We must select ourselves as the character by which we must play the game of life. We must not be caught trying to play as another person's character. It is impossible.""",
"""Where else can you go from here? You've hit rock bottom and even though there are always people who are worse off than you, nevertheless, you're at your lowest point now. You're familiar with the pangs of an empty stomach and accustomed to the internal war that goes on in the mind of the broken. You're at your wit's end. Where else can you go but up? What other direction can you move but forwards? Forward unto the prize, eyes locked on the light at the end of the tunnel. Through all the darkness you have acquired tunnel vision. Your aim is timed and your strike is as deadly as the sharp shooter. You're looking unto Jesus, the author and finisher of your faith. You've begun a new journey of discovery into yourself and the finds are monumental. You're not outside or on the touchlines but inside and in the fight for life, this living battleground. You've understudied charity and you understand the value of giving back. You're not a victim looking for pity anymore but instead it is from your hands that good gifts are given out. You have sharpened your self-esteem and you're primed for any and all opportunities. This will demand 10,000 hours of painting and sculpting. 10,000 hours until you break open your Pandora's box and gain access to supernatural powers. When you master the way of the sword, the way of the pen, when your fingers are taught how to battle and your arms are taught how to war. Look inside. Tell me what you see.""",
"""I wonder how many people are out there like me, in such a desperate need for a father, for instruction. I reckon the numbers are mind-boggling. I am at an impasse. I have come into the consciousness that I am the Spirit, that I am the Son and that I am the Father. My mind is one with the idea that I am God, or at the least, I am the complete reflection and expression of God. I am at a crossroad at the junction where the bus of transformation carries its passengers. Like the wind, I am on a journey without a fixed destination, an unending trip into realms in other dimensions. I am plagued with questions so I turn to the spirit within me in earnest meditation. I am searching for answers, probing for clues, looking for signs and signals from within, seeking out the truth. It is a journey into places where time does not exist, where space is of no consequence, through realms outside the confines of time and space, on an ultimate search into God. I am standing on the ledge of a new threshold and all I need is faith to take the next step. The first step of flight up into new atmospheres. Flesh and Time are my only burdens. They are but evidence that I exist in this physical realm. And even then, my spirit is not bound by flesh nor by time. I am Spirit, I am Son, I am Father. I am the image and likeness of all three in one."""
]

def get_relevant(query):
    q = query.lower()
    scored = []
    for w in WRITINGS:
        score = sum(1 for word in q.split() if len(word)>3 and word in w.lower())
        if "pain" in q and "pain" in w.lower(): score+=2
        if "word" in q and "word" in w.lower(): score+=2
        if "family" in q and "family" in w.lower(): score+=3
        scored.append((score + random.random()*0.5, w))
    scored.sort(reverse=True)
    return scored[0][1], scored[1][1]

def chat_fn(msg, hist):
    a,b = get_relevant(msg)
    opener = random.choice(["Here's what I wrote about that —","I lived this —","From my pages:","Listen:"])
    return f"{opener}\n\n{a}\n\n---\n{b[:600]}"

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# DAVID ALEXANDER AI\n### I set myself ablaze for the world to watch me burn\nSelf Therapy. What's on your mind today?")
    gr.ChatInterface(chat_fn, examples=["I feel pain", "I feel isolated", "How do I change my words?", "Life feels like a game"])

demo.launch(server_name="0.0.0.0", server_port=int(os.environ.get("PORT", 7860)))r image likeness all three different characteristics functions same manifestation operations not my flesh I am Spirit flesh know spirit manifests first as Son when comes into world within Son resides Father which Son destined transformed into over time even when Son transformed into Father Son still resides within Father like Father within Son beginning Father Son one same Spirit same Spirit within Man Man made Image Likeness God.""",
"""Knowledge sweeter mind spirit than sweet drinks food tongue deep knowledge deeper things life discoveries more stimulating consciousness than physical sensation body knowledge love bonds us all love by which atoms body joined one another strong binds all every component creation love exists within all creation love by which all creation made knowledge sweeter honey importance bees knowledge language love speaks heart interfaces soul knowledge life death spirit brings dead spirit back life knowledge true source life heartbeat spirit Life life knowledge sets free ageless bondage arms proper tools navigation knowledge carries power transformation takes through process genuine change love corrects when go wrong teaches righteousness Father knowledge opens channels spirit from which immense power begins."""
]

def get_relevant(query):
    q = query.lower()
    # score by overlap + random to avoid same answer
    scored = []
    for w in WRITINGS:
        score = sum(1 for word in q.split() if len(word)>3 and word in w.lower())
        # boost if emotion matches
        if any(k in q for k in ["pain","hurt","broken"]):
            if "pain" in w.lower() or "rock" in w.lower(): score+=2
        if any(k in q for k in ["word","speak","write"]):
            if "word" in w.lower(): score+=3
        scored.append((score + random.random(), w))
    scored.sort(reverse=True)
    return [w for s,w in scored[:2]]

def chat_fn(msg, hist):
    picks = get_relevant(msg)
    # make it dynamic
    intro = random.choice([
        "Look —",
        "Listen to this:",
        "This is where it clicks —",
        "From my own pages —",
        "I wrote this when I was in it:"
    ])
    return f"{intro}\n\n{picks[0][:1200]}\n\n---\n\nAnd this:\n{picks[1][:800]}\n\n🔥 Action: Take one line and speak it out loud today. Word made flesh."

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# DAVID ALEXANDER AI\n### I set myself ablaze for the world to watch me burn\nSelf Therapy. Whats on your mind today?.")
    gr.ChatInterface(chat_fn, examples=["I'm stuck", "Talk about words", "I feel pain", "How do I reprogram?"])

demo.launch(server_name="0.0.0.0", server_port=int(os.environ.get("PORT", 7860)))
