import gradio as gr, os, random

WRITINGS = [
"""Your thoughts have now been given form and manifested. Your speech sets direction for consciousness. Death and life are in power of tongue. By thy words justified condemned. Words are crystallized vibrations amplified frequency of thoughts. Stories you repeatedly tell about yourself becomes lens you perceive reality. How you think and vocalise is your creative force. Most people complain, low self esteem, superiority inferiority, talk negatively. Miracles begin when you change how you speak about yourself. Words carry synchronicity. Word becomes outward evidence inward shift begun. Man that thinks he can and cannot are both right.""",
"""God have mercy my head wants to explode blood pumping ferociously anticipation all time high future infinite possibilities. Time to go backend of programming rewrite script of life lived until now. Studying different programming languages become versatile writer fluent in deep languages. Total reprogramming thoughts mentality characteristics mindset. New strings variables functions brand new commands proper organization cascaded concatenations compartmentalization new structure. So far error returns mistakes code mental drives maliciously corrupted need meticulous bug search intensive virus scan. Rebuild from scratch testing troubleshooting frequently. Get with program literally metaphorically technologically. Power programming power create new immortal worlds.""",
"""Speaker is life changer destinies resting on structure delivery of every word. Contagious energy transferred through vibrations words depth passion intense light fire hearts generations. Cadence of God hand ready writer pen skilled poet voice great commander. Does not joke with words uses silence as weapon so when whispers voice becomes loudest in room. Like water takes form container adapts like water high pressure applied transformed suddenly weapon deadly spear. Art of war is Speaking. No one can ignore potency. Medium energy transferred power precision power revolutions upon tongue lips coated gold. Wordsmith painting pictures vivid mind blind see crafting words spells that break spells bondage liberating generation.""",
"""Finally I have Words weapon massive destruction power unlimited creation craving now infinite possibilities prove truth study show myself approved master without shame. Crafting Creation Destruction Joy Sorrow fiery arrows soul spirit breakdown generational walls unite generations Pleasure Pain heal broken hearted rebuke pompous. Like skilled farmer sowing seeds fertile grounds words are seeds open hearted fertile grounds destined take root yield fruits. Pain dragon coiling soul? Pain isn't enemy most demanding teacher compels step out shadows comfort zones master pushes beyond limits attain higher mastery than himself.""",
"""What is this stream energy crystallizes mind waves ripples within into other dimensions inward pull magnetic thermodynamical converting one form to another astronomical Could this be energy of God fire consumes within burns infestation licks infections away fire never kill with water burns fears crisp turns pain ash fan fires spirit weaknesses turn strength sorrows joy hunger more fire yearning screaming whispers like thunder harken or nonchalant?""",
"""What you need over talent is Vision able see yourself doing it first details. Stop habit also need vision seeing self not doing that. If cannot fathom cannot become. If do not have vision never become reality power sight seeing.""",
"""It hits hard Reality rings chains energy heavy arms heavy enough pull shoulders joint but doesn't weighs back neck sharp object trying pass chest behind sharp enough drive crazy but doesn't ghastly collision overdose eye opening drug shocks fingertips movie can't stop acting set can't escape script own writing sack solidified cement chest bone stuck throat swallow Only mortal death separate from plane reality.""",
"""Men disturbed not by things but opinion about things Epictetus. Be cheerful friendly less critical more tolerant place best interpretation act as if success inevitable already personality want practice acting like feeling like don't let opinion colour facts pessimistically smile 3 times daily react calmly intelligently ignore pessimistic negative facts cannot change Happiness requires problems plus mental attitude ready meet distress with action toward solution change mental attitude fear to fight ruling thoughts principal concern.""",
"""Create powerful protective social mental structure insulating pressures modern world What they did make us loose value family extended family broke us up Now family function once year don't want part isolated facing modern world alone want modern car house status when show up everyone respect least things should be mind Cut off essential experiences some afraid too exposed unable tolerate isolated under burden shame more keep away more shame sinks pride if cannot humble before family condescend level generations after how learn humility outside If too afraid ego poked how face constructive brutal criticism outside Family first place learn happiness not external but within And cut off how learn purity happiness unbiased Love chased external temporary. Child power drive away depression child lights up return spirit lifted problems disappear curious nature moment comments ignite laughter rolling memories beauty childhood wonder joy bursting energy running jumping brand new machine minds creating recreating questioning wildest conclusions unable hold grudge moment unending lists requests forgetting Jet palace meal crying laughing same person beautiful addition cure depression isolation loneliness fulfilling.""",
"""Don't you have more than enough reasons shaken awake How many more volts life enough smoke you deep sleep You have everything you need more will of mind creative ability endlessly spontaneous within first manifesting physical You are all it takes Disgust Desire Decision path no lion ever threaded chicken never know path searching testing studying show oneself approved master without shame Two cannot walk road together Every man by himself only voyage untold discovery exciting adventure destiny God.""",
"""Life is game many not yet playing controller hands other person not yet playing field coming conscious realization life like Naruto Solo leveling continually grow spiritual energy ability chakra cultivated daily consistent practice secret technique Imagine everyone could see progress levels above heads percent growth each ability. Life game levelling up rack points ascend pyramid survival or left bottom comfort zones settling scraps required control pick up control pad consciously press start enter adventure searching hidden gems treasures increasing Mana chi acquiring abilities circumvent trials master terrain conquer select ourselves as character not be caught playing as another persons character impossible play as own characters own given abilities level up practice hone skills.""",
"""Where else can you go You've hit rock bottom pangs empty stomach internal war broken mind wits end Where else but up what direction but forwards Forward prize Eyes locked light end tunnel darkness acquired tunnel vision aim timed strike deadly sharp shooter sense direction spot on looking unto Jesus author finisher faith begun new journey discovery finds monumental found understanding within good courage know where stand Not outside touchlines but inside fight living battleground understudied charity value giving back not victim looking pity handouts instead from hands good gifts given sharpened self esteem primed opportunities sound mind Godly characteristics Righteous benevolent ways see understand pain others able look outside objectively become master self can be master others Every word new meaning deeper previously invincible understand faith love patience etc different. What required conscious action will spirit execute operation calling within paint vivid picture imagination self crave opposite image self disgusts craft precise sculpture desires 4 dimensional 10000 hours painting sculpting complexity genius unlocked break Pandora box access supernatural powers master way sword way pen hands ready writer fingers taught battle arm taught war Only option move forwards upwards look forward new realties create look upwards hills whence help attuned heavenly Father craves perfect Son study show approved keep words close guard heart diligence approach throne grace fear trembling reverence humility ascend mountain Look inside Tell me what you see pattern wrong need switch swinging side side no direction stuck old ways only existing never living point meaning life Questions pillage mind eyes need sight mind meditating outside influence time Life attacking spears intent devouring force life ALL SPARK time separate truth lies hold facts raw untainted reconnect infinite force know yourself test thoughts Time essence No excuses.""",
"""I wonder how many out there like me desperate need father instruction numbers mind boggling impasse consciousness I am Spirit Son Father mind one idea I am God complete reflection expression God crossroad junction bus transformation carries passengers Like wind journey without fixed destination unending trip realms other dimensions plagued questions turn spirit within earnest meditation searching answers probing clues looking signs signals within seeking truth journey like none adventure into places time does not exist space no consequences outside confines time space ultimate search into God For God standing ledge new threshold need faith next step first step flight new atmospheres below which mind formerly dwelt I am God God is Spirit Son Father All in one What better way answer What is Man Flesh Time only burdens evidence exist physical realm even then spirit not bound flesh nor time substance source life true nature collective consciousness core I am Spirit Son Father image likeness all three different characteristics functions same manifestation operations not my flesh I am Spirit flesh know spirit manifests first as Son when comes into world within Son resides Father which Son destined transformed into over time even when Son transformed into Father Son still resides within Father like Father within Son beginning Father Son one same Spirit same Spirit within Man Man made Image Likeness God.""",
"""Knowledge sweeter mind spirit than sweet drinks food tongue deep knowledge deeper things life discoveries more stimulating consciousness than physical sensation body knowledge love bonds us all love by which atoms body joined one another strong binds all every component creation love exists within all creation love by which all creation made knowledge sweeter honey importance bees knowledge language love speaks heart interfaces soul knowledge life death spirit brings dead spirit back life knowledge true source life heartbeat spirit Life life knowledge sets free ageless bondage arms proper tools navigation knowledge carries power transformation takes through process genuine change love corrects when go wrong teaches righteousness Father knowledge opens channels spirit from which immense power begins."""
]

def get_relevant(query):
    q = query.lower()
    # score by overlap + random to avoid same answer
    scored = []
    for w in WRITINGS:
        score = sum(1 for word in q.split() if len(word)>3 and word in w.lower())
        # boost if emotion matches
        if any(k in q for k in ["pain","hurt","broken"]):
            if "pain" in w.lower() or "rock" in w.lower(): score+=2
        if any(k in q for k in ["word","speak","write"]):
            if "word" in w.lower(): score+=3
        scored.append((score + random.random(), w))
    scored.sort(reverse=True)
    return [w for s,w in scored[:2]]

def chat_fn(msg, hist):
    picks = get_relevant(msg)
    # make it dynamic
    intro = random.choice([
        "Look —",
        "Listen to this:",
        "This is where it clicks —",
        "From my own pages —",
        "I wrote this when I was in it:"
    ])
    return f"{intro}\n\n{picks[0][:1200]}\n\n---\n\nAnd this:\n{picks[1][:800]}\n\n🔥 Action: Take one line and speak it out loud today. Word made flesh."

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# DAVID ALEXANDER AI\n### I set myself ablaze for the world to watch me burn\nNo numbers. Just my actual words, dynamic.")
    gr.ChatInterface(chat_fn, examples=["I'm stuck", "Talk about words", "I feel pain", "How do I reprogram?"])

demo.launch(server_name="0.0.0.0", server_port=int(os.environ.get("PORT", 7860)))
